---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: awscognito
spec:
  image: gcr.io/triggermesh/awscognito:latest
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: awscreds
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: awscreds
          key: aws_secret_access_key
    - name: AWS_REGION
      value: us-west-2
    - name: IDENTITY_POOL_ID
      value: us-west-2:your-identity-pool-id