apiVersion: v1
kind: Service
metadata:
  name: snssource
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "sns.test-topic.testchannel.default.sources.rsmitty.cloud"
spec:
  selector:
    source: sns
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snssource
spec:
  selector:
    matchLabels:
      source: sns
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        source: sns
    spec:
      volumes:
      - name: sns-creds
        secret:
          secretName: snscreds
      containers:
      - name: subscriber
        image: gcr.io/triggermesh/snssource:latest
        volumeMounts:
        - name: sns-creds
          mountPath: /.aws
        env:
        - name: AWS_CREDS
          value: /.aws/credentials
        - name: AWS_REGION
          value: us-east-2
        - name: CHANNEL
          value: testchannel
        - name: TOPIC
          value: test-topic
        - name: DOMAIN
          value: sources.rsmitty.cloud
        - name: PROTOCOL
          value: http
        - name: DEBUG
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
